In [4]:
import numpy as np

In [2]:
#creating numpy arrays
a_list=[1,3,5]
np.array(a_list)

array([1, 3, 5])

In [6]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [8]:
np.random.normal(0,1,(2,2))#2-d random normal distribuition numpy array whose mean is @0,sd=1

array([[ 1.75575841,  1.7606978 ],
       [ 0.12293106, -0.81040121]])

In [16]:
#creating 3 random arrays 1d,2d,3d
np.random.seed(0)
arr1=np.random.randint(10,size=6)
arr2=np.random.randint(10,size=(3,4))
arr3=np.random.randint(10,size=(3,4,5))#3 rows 4 cols & 5 elements of the list

In [12]:
print("1 D array:\n",arr1)

1 D array:
 [5 0 3 3 7 9]


In [14]:
print(arr1)

[5 0 3 3 7 9]


In [13]:
print("last element of 1D :\n",arr1[-1])#slicing & dicing

last element of 1D :
 9


In [17]:
print('2d array:\n',arr2)

2d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [19]:
print('slicing 2d array to get 2nd and 3nd row:\n',arr2[1:])

slicing 2d array to get 2nd and 3nd row:
 [[7 6 8 8]
 [1 6 7 7]]


In [21]:
print('need alternate cols:\n',arr2[:,::2])

need alternate cols:
 [[3 2]
 [7 8]
 [1 7]]


comparison & masking

In [22]:
ar=np.array([1,2,3,4])

In [23]:
ar>=4

array([False, False, False,  True])

In [28]:
arr=np.random.randint(10,size=(3,4))
arr

array([[3, 2, 3, 4],
       [1, 2, 9, 1],
       [4, 6, 8, 2]])

In [26]:
np.sum(arr>9)

0

In [34]:
np.all(arr>=9)

False

In [33]:
np.any(arr>=9)

True

# Masking


In [36]:
test_scores=np.random.randint(100,size=(30))
test_scores

array([96,  4, 67, 11, 86, 77, 75, 56, 16, 24, 29, 21, 25, 80, 60, 61, 83,
       33, 32, 70, 85, 31, 13, 71, 56, 24, 79, 41, 18, 40])

In [37]:
mask=test_scores>35#pass
test_scores[mask]

array([96, 67, 86, 77, 75, 56, 80, 60, 61, 83, 70, 85, 71, 56, 79, 41, 40])